/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgressIndexRouteImport } from './routes/progress/index'
import { Route as ProgressTopicIdRouteImport } from './routes/progress/$topicId'
import { Route as TopicsTopicIdIndexRouteImport } from './routes/topics/$topicId/index'
import { Route as TopicsTopicIdMcqRouteImport } from './routes/topics/$topicId/mcq'
import { Route as TopicsTopicIdFlashcardsRouteImport } from './routes/topics/$topicId/flashcards'
import { Route as TopicsTopicIdFactsRouteImport } from './routes/topics/$topicId/facts'
import { Route as TopicsTopicIdNavToolIdRouteImport } from './routes/topics/$topicId/nav.$toolId'
import { Route as TopicsTopicIdModeCompleteRouteImport } from './routes/topics/$topicId/$mode.complete'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressTopicIdRoute = ProgressTopicIdRouteImport.update({
  id: '/progress/$topicId',
  path: '/progress/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdIndexRoute = TopicsTopicIdIndexRouteImport.update({
  id: '/topics/$topicId/',
  path: '/topics/$topicId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdMcqRoute = TopicsTopicIdMcqRouteImport.update({
  id: '/topics/$topicId/mcq',
  path: '/topics/$topicId/mcq',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdFlashcardsRoute = TopicsTopicIdFlashcardsRouteImport.update({
  id: '/topics/$topicId/flashcards',
  path: '/topics/$topicId/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdFactsRoute = TopicsTopicIdFactsRouteImport.update({
  id: '/topics/$topicId/facts',
  path: '/topics/$topicId/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdNavToolIdRoute = TopicsTopicIdNavToolIdRouteImport.update({
  id: '/topics/$topicId/nav/$toolId',
  path: '/topics/$topicId/nav/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdModeCompleteRoute =
  TopicsTopicIdModeCompleteRouteImport.update({
    id: '/topics/$topicId/$mode/complete',
    path: '/topics/$topicId/$mode/complete',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/progress/$topicId': typeof ProgressTopicIdRoute
  '/progress/': typeof ProgressIndexRoute
  '/topics/$topicId/facts': typeof TopicsTopicIdFactsRoute
  '/topics/$topicId/flashcards': typeof TopicsTopicIdFlashcardsRoute
  '/topics/$topicId/mcq': typeof TopicsTopicIdMcqRoute
  '/topics/$topicId/': typeof TopicsTopicIdIndexRoute
  '/topics/$topicId/$mode/complete': typeof TopicsTopicIdModeCompleteRoute
  '/topics/$topicId/nav/$toolId': typeof TopicsTopicIdNavToolIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/progress/$topicId': typeof ProgressTopicIdRoute
  '/progress': typeof ProgressIndexRoute
  '/topics/$topicId/facts': typeof TopicsTopicIdFactsRoute
  '/topics/$topicId/flashcards': typeof TopicsTopicIdFlashcardsRoute
  '/topics/$topicId/mcq': typeof TopicsTopicIdMcqRoute
  '/topics/$topicId': typeof TopicsTopicIdIndexRoute
  '/topics/$topicId/$mode/complete': typeof TopicsTopicIdModeCompleteRoute
  '/topics/$topicId/nav/$toolId': typeof TopicsTopicIdNavToolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/progress/$topicId': typeof ProgressTopicIdRoute
  '/progress/': typeof ProgressIndexRoute
  '/topics/$topicId/facts': typeof TopicsTopicIdFactsRoute
  '/topics/$topicId/flashcards': typeof TopicsTopicIdFlashcardsRoute
  '/topics/$topicId/mcq': typeof TopicsTopicIdMcqRoute
  '/topics/$topicId/': typeof TopicsTopicIdIndexRoute
  '/topics/$topicId/$mode/complete': typeof TopicsTopicIdModeCompleteRoute
  '/topics/$topicId/nav/$toolId': typeof TopicsTopicIdNavToolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/progress/$topicId'
    | '/progress/'
    | '/topics/$topicId/facts'
    | '/topics/$topicId/flashcards'
    | '/topics/$topicId/mcq'
    | '/topics/$topicId/'
    | '/topics/$topicId/$mode/complete'
    | '/topics/$topicId/nav/$toolId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/progress/$topicId'
    | '/progress'
    | '/topics/$topicId/facts'
    | '/topics/$topicId/flashcards'
    | '/topics/$topicId/mcq'
    | '/topics/$topicId'
    | '/topics/$topicId/$mode/complete'
    | '/topics/$topicId/nav/$toolId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/progress/$topicId'
    | '/progress/'
    | '/topics/$topicId/facts'
    | '/topics/$topicId/flashcards'
    | '/topics/$topicId/mcq'
    | '/topics/$topicId/'
    | '/topics/$topicId/$mode/complete'
    | '/topics/$topicId/nav/$toolId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProgressTopicIdRoute: typeof ProgressTopicIdRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
  TopicsTopicIdFactsRoute: typeof TopicsTopicIdFactsRoute
  TopicsTopicIdFlashcardsRoute: typeof TopicsTopicIdFlashcardsRoute
  TopicsTopicIdMcqRoute: typeof TopicsTopicIdMcqRoute
  TopicsTopicIdIndexRoute: typeof TopicsTopicIdIndexRoute
  TopicsTopicIdModeCompleteRoute: typeof TopicsTopicIdModeCompleteRoute
  TopicsTopicIdNavToolIdRoute: typeof TopicsTopicIdNavToolIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/$topicId': {
      id: '/progress/$topicId'
      path: '/progress/$topicId'
      fullPath: '/progress/$topicId'
      preLoaderRoute: typeof ProgressTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId/': {
      id: '/topics/$topicId/'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId/'
      preLoaderRoute: typeof TopicsTopicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId/mcq': {
      id: '/topics/$topicId/mcq'
      path: '/topics/$topicId/mcq'
      fullPath: '/topics/$topicId/mcq'
      preLoaderRoute: typeof TopicsTopicIdMcqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId/flashcards': {
      id: '/topics/$topicId/flashcards'
      path: '/topics/$topicId/flashcards'
      fullPath: '/topics/$topicId/flashcards'
      preLoaderRoute: typeof TopicsTopicIdFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId/facts': {
      id: '/topics/$topicId/facts'
      path: '/topics/$topicId/facts'
      fullPath: '/topics/$topicId/facts'
      preLoaderRoute: typeof TopicsTopicIdFactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId/nav/$toolId': {
      id: '/topics/$topicId/nav/$toolId'
      path: '/topics/$topicId/nav/$toolId'
      fullPath: '/topics/$topicId/nav/$toolId'
      preLoaderRoute: typeof TopicsTopicIdNavToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId/$mode/complete': {
      id: '/topics/$topicId/$mode/complete'
      path: '/topics/$topicId/$mode/complete'
      fullPath: '/topics/$topicId/$mode/complete'
      preLoaderRoute: typeof TopicsTopicIdModeCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProgressTopicIdRoute: ProgressTopicIdRoute,
  ProgressIndexRoute: ProgressIndexRoute,
  TopicsTopicIdFactsRoute: TopicsTopicIdFactsRoute,
  TopicsTopicIdFlashcardsRoute: TopicsTopicIdFlashcardsRoute,
  TopicsTopicIdMcqRoute: TopicsTopicIdMcqRoute,
  TopicsTopicIdIndexRoute: TopicsTopicIdIndexRoute,
  TopicsTopicIdModeCompleteRoute: TopicsTopicIdModeCompleteRoute,
  TopicsTopicIdNavToolIdRoute: TopicsTopicIdNavToolIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
